// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/yunzhubanban/server/app/model/internal"
)

// Classes is the golang structure for table classes.
type Classes internal.Classes

// Fill with you ideas below.
