// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Classes is the golang structure for table classes.
type Classes struct {
	Id     uint   `orm:"id,primary"     json:"id"`     // 标识符（班级号）
	Name   string `orm:"name"           json:"name"`   // 班级
	Config string `orm:"config,primary" json:"config"` // 班级配置文件
}
