// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"github.com/yunzhubanban/server/app/dao/internal"
)

// classesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type classesDao struct {
	internal.ClassesDao
}

var (
	// Classes is globally public accessible object for table classes operations.
	Classes = classesDao{
		internal.Classes,
	}
)

// Fill with you ideas below.
